# Generated by Django 3.0.6 on 2020-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='login',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='room',
        ),
    ]
