# Generated by Django 3.0.6 on 2020-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200621_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='name',
            field=models.CharField(db_index=True, default='none', max_length=250),
            preserve_default=False,
        ),
    ]
